"""
Clickstream Batch Orchestration DAG (Architecture B).

Runs the Silver -> Gold aggregation via spark-submit against the existing
Spark Standalone cluster, then verifies that the Gold layer bucket contains
objects. Manual trigger only (schedule=None) -- flip to a cron expression
(e.g. `0 * * * *`) for a scheduled pipeline.

Producer events are continuously generated by the `producer` container in both
architectures, so there is no need for the batch DAG to run its own producer
burst. The DAG simply aggregates whatever data is currently in the Silver layer.

Task flow (see docs/infrastructure.md for the diagram):

  run_batch_job (BashOperator, spark-submit) --> verify_gold_layer (BashOperator)
"""

from datetime import datetime

from airflow.sdk import DAG
from airflow.operators.bash import BashOperator

# Kept in sync with:
#   docker-compose.yml (streaming-job --packages, line ~95)
#   src/batch/batch_job.py spark.jars.packages
# A follow-up could centralise these coordinates in a shared file.
SPARK_PACKAGES = (
    "io.delta:delta-spark_2.12:3.2.0,"
    "org.apache.hadoop:hadoop-aws:3.3.4,"
    "com.amazonaws:aws-java-sdk-bundle:1.12.262"
)

BATCH_JOB_PATH = "/opt/airflow/dags/src/batch/batch_job.py"
SPARK_MASTER = "spark://spark-master:7077"
GOLD_BUCKET_LIST_URL = (
    "http://localstack:4566/user-behavior-analytics-gold?list-type=2&max-keys=5"
)

default_args = {
    "owner": "airflow",
    "depends_on_past": False,
    "retries": 0,
}

dag = DAG(
    "clickstream_batch",
    default_args=default_args,
    description=(
        "Runs Silver -> Gold aggregation via spark-submit against the Spark "
        "Standalone cluster, then verifies Gold-layer objects exist on S3."
    ),
    schedule=None,
    start_date=datetime(2026, 4, 14),
    catchup=False,
    max_active_runs=1,
    tags=["architecture-b", "batch", "gold"],
)

# Config notes:
#
# --conf spark.driver.extraJavaOptions=-Divy.home=/tmp/ivy2
#   Redirects Ivy's local cache to the shared /tmp/ivy2 volume (ivy2-cache
#   docker volume). Without it, the driver re-downloads ~200MB of Maven JARs
#   on every run.
#
# --conf spark.cores.max=1 --conf spark.executor.memory=512m
#   The Spark worker has 2 cores / 2G RAM. The streaming app is capped at
#   1 core so it never consumes the whole cluster; this batch submit is
#   capped the same way so it can always grab the remaining core alongside
#   streaming. Without these caps, if the batch app started before streaming
#   it would grab both cores and leave streaming unable to register.
run_batch_job = BashOperator(
    task_id="run_batch_job",
    bash_command=f"""
set -euo pipefail

spark-submit \
    --master {SPARK_MASTER} \
    --name ClickstreamBatch \
    --conf spark.driver.extraJavaOptions=-Divy.home=/tmp/ivy2 \
    --conf spark.cores.max=1 \
    --conf spark.executor.memory=512m \
    --packages {SPARK_PACKAGES} \
    {BATCH_JOB_PATH}
""",
    dag=dag,
)

verify_gold_layer = BashOperator(
    task_id="verify_gold_layer",
    bash_command=f"""
set -euo pipefail

echo "Listing Gold-layer bucket..."
curl -sf '{GOLD_BUCKET_LIST_URL}' | python3 -c "
import sys
content = sys.stdin.read()
n = content.count('<Key>')
print(f'Gold layer: {{n}} objects')
sys.exit(0 if n > 0 else 1)
"
""",
    dag=dag,
)

run_batch_job >> verify_gold_layer
