connector.name=delta-lake
hive.metastore=file
hive.metastore.catalog.dir=s3a://user-behavior-analytics-silver/
hive.s3.aws-access-key=test
hive.s3.aws-secret-key=test
hive.s3.endpoint=http://localstack:4566
hive.s3.path-style-access=true
hive.s3.ssl.enabled=false
